// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdH7OR2xHXJebHnAxxxeQsbq_IoOFRPwA',
    appId: '1:546605812428:android:9c8393ed245d6659ddd069',
    messagingSenderId: '239787574751',
    projectId: 'uoonsseller-b31ca',
    authDomain: 'mangoai-9c366.firebaseapp.com',
    storageBucket: 'uoonsseller-b31ca.appspot.com',
    measurementId: 'G-XM451ZVRPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdH7OR2xHXJebHnAxxxeQsbq_IoOFRPwA',
    appId: '1:546605812428:android:9c8393ed245d6659ddd069',
    messagingSenderId: '239787574751',
    projectId: 'uoonsseller-b31ca',
    storageBucket: 'uoonsseller-b31ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdH7OR2xHXJebHnAxxxeQsbq_IoOFRPwA',
    appId: '1:546605812428:android:9c8393ed245d6659ddd069',
    messagingSenderId: '239787574751',
    projectId: 'uoonsseller-b31ca',
    storageBucket: 'uoonsseller-b31ca.appspot.com',
    iosClientId: '239787574751-qo5ph6mcc1j770gglp6bommrekeob706.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangoAi',
  );


}